const more = document.getElementsByClassName('more')
const img = document.getElementsByTagName('img')
const plus = document.getElementsByClassName('plus')
const join_btn = document.getElementById('join_btn')
const ul = document.getElementsByTagName('ul')
const li = document.getElementsByTagName('li')
console.log(more)
console.log(more.innerHTML)
console.log(img)
console.log(plus)
console.log(join_btn)
console.log(ul)
console.log(li, li[0],li[1],li[2],li[3],li[4],li[5])